name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: gosnap.exe
            asset_name: gosnap-windows-amd64.exe
          - os: ubuntu-latest
            artifact_name: gosnap
            asset_name: gosnap-linux-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Verify Go environment
        run: |
          go version
          go env
          ls -la
        shell: bash

      - name: Create bin directory
        run: mkdir -p bin
        shell: bash

      - name: Build binary
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmd /c build.bat
          else
            GOOS=linux go build -o bin/gosnap -a -gcflags=all="-l -B" -ldflags="-w -s" -trimpath -buildvcs=false || { echo "Linux build failed"; exit 1; }
          fi
        shell: bash

      - name: Verify build output
        run: |
          ls -la bin/
          if [ ! -f bin/${{ matrix.artifact_name }} ]; then
            echo "Error: Build output bin/${{ matrix.artifact_name }} not found"
            exit 1
          fi
        shell: bash

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true