name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            ext: .exe
            binary_name: gosnap-windows-amd64.exe
            build_cmd: go build -o gosnap-windows-amd64.exe -ldflags="-s -w" -trimpath -buildvcs=false
          - os: ubuntu-latest
            ext: ""
            binary_name: gosnap-linux-amd64
            build_cmd: go build -o gosnap-linux-amd64 -ldflags="-s -w" -trimpath -buildvcs=false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: ${{ matrix.build_cmd }}

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.binary_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}